version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    expose:
      - "8080"
    volumes:
      - ./:/var/www
    environment:
      # Puedes configurar variables de entorno aquí o hacerlo directamente en Coolify
      APP_ENV: production
      APP_DEBUG: "false"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
